name: Build (Linux GCC)

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  linux-gcc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install GCC 14
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
          sudo apt update
          sudo apt install -y g++-14

      - name: Install Wayland + X11 deps for GLFW
        run: |
          sudo apt update
          sudo apt install -y \
            libwayland-dev \
            libwayland-bin \
            wayland-protocols \
            libxkbcommon-dev \
            xorg-dev

      - name: Configure
        run: cmake -B build -DCMAKE_CXX_COMPILER=g++-14 -DCMAKE_C_COMPILER=gcc-14 -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --parallel
